filebeat.inputs:
- type: log
  json.keys_under_root: true
  json.message_key: log
  enabled: true
  encoding: utf-8
  document_type: docker
  paths:
    - '/var/www/symfony/logs/*.log'

output.logstash:
  hosts: ["logstash:5000"]